# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-06 10:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_validation_regex', models.CharField(blank=True, max_length=700, null=True)),
                ('answer_field_type', models.CharField(choices=[('text', 'Text'), ('boolean', 'Boolean'), ('radio', 'Radio Box'), ('checkbox', 'Checkbox'), ('select', 'Drop-down list')], max_length=200)),
                ('answer_text', models.CharField(max_length=700)),
                ('date_answered', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('question_text', models.CharField(max_length=700)),
                ('date_created', models.DateTimeField(default=datetime.datetime.now)),
                ('after', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.Question')),
            ],
            options={
                'ordering': ('questionaire', 'after'),
            },
        ),
        migrations.CreateModel(
            name='Questionaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=700)),
                ('description', models.CharField(max_length=700)),
                ('date_created', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='questionaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.Questionaire'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.Question'),
        ),
    ]
