# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-06 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_auto_20170806_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='client_token',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='wait_for_response',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='questionaire',
            name='name',
            field=models.CharField(max_length=700, unique=True),
        ),
    ]
