# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-06 14:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=700)),
                ('datetime_start', models.DateTimeField(default=datetime.datetime.now)),
                ('datetime_end', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('client_token', models.CharField(blank=True, max_length=100, null=True)),
                ('bot', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Verbiage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('text', models.CharField(max_length=100)),
                ('agent', models.CharField(max_length=100)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='channel.Conversation')),
            ],
        ),
    ]
